### ISSUE TITLE
Interface for passing identifier information

### ISSUE THREAD

**Issue by physikerwelt** [dginev/LaTeXML-Plugin-ltxpsgi#7] opened 2015-03-23 17:06 UTC
@alexeygrigorev is about to continue the [MLP Project](https://github.com/TU-Berlin/project-mlp)
Currently identifier descriptions are provided abusing the title field.
https://github.com/wikimedia/mediawiki-extensions-MathSearch/blob/c154b4bc1c52a1260fe3df8e0cf21dfe0769d42a/MathObject.php#L295
@dginev I wonder if you have general thoughts about passing meta information on an individual formula to latexml?

**Comment by dginev** [comment] 2015-03-23 17:19
"meta" sounds like a good application of lxRDFa.sty, you can embed any RDFa information in the HTML document. I haven't tried applying that to formulas, but it should be working out of the box already.

**Comment by physikerwelt** [comment] 2015-03-23 21:58
Thanks that sound promising. However, I don't really get that with the xpath.
For example if we had for instance a formula $E=mc^2$ and our NLP pipeline indicates that the probability that $E$ stands for Energy (https://www.wikidata.org/wiki/Q11379) we would like to add this info to the locations of all $E$ in that equation.
In the example I manged to assign key value pairs to the whole equation but not individual identifiers ... (they were removed by latexmlpost... but that's not necessarily a bad thing)
https://gist.github.com/physikerwelt/bd83db0212f85010d518

**Comment by dginev** [comment] 2015-03-24 18:08
I am assuming the Math post-processing may need a touch to copy over the RDFa attributes. @brucemiller has a better overview on that front, since he has been redesigning parts of the math attributes recently.

**Comment by dginev** [comment] 2015-03-24 18:20
I can confirm that RDFa positioned in math floats to the ancestor <XMath> element and then gets omitted in post-processing. Sounds like something to work on.

Fine-grained RDFa in MathML is super fancy btw, pretty sure you guys will be breaking ground in using that. Thumbs up. But this is the wrong place for this discussion, so I will ruthlessly close this issue :)

**Closed by dginev** 2015-03-24 18:20 UTC
Labels: question

**Comment by physikerwelt** [comment] 2015-03-24 21:44
Just for search engines. @brucemiller pointed me to
```
\documentclass{article}
\usepackage{latexml}
\begin{document}
	\lxDeclare[role=FUNCTION]{$f$}%
	$f(a+b)=g(a+b)$
\end{document}
```

**Comment by physikerwelt** [comment] 2015-03-24 22:04
and adjusted to the original example
```
\documentclass{article}
\usepackage{latexml}
\begin{document}
	\lxDeclare[meaning=Energy]{$E$}%
	\lxDeclare[meaning=mass]{$m$}
	\lxDeclare[meaning=speed-of-light,role=CONSTANT]{$c$}
	$E=mc^2$
\end{document}
```
The power still generates an 
```
        <apply>
          <csymbol cd="ambiguous">superscript</csymbol>
```
However, it's much better than before. Now I'll try to get that through LaTeXML-Plugin-ltxpsgi
